### ISSUE TITLE
Issue when using AWS SDK dependency

### ISSUE THREAD

**Issue by andersforsell** [web-padawan/polymer3-webpack-starter#10]
Thanks for putting together a webpack config for Polymer 3.
I have no experience using Webpack, but realize that I need to use this since I am running into various problems with the Polymer tools .

I am struggling to get it working with some additional AWS dependencies when building for production:

```
ERROR in ./node_modules/aws-sdk/lib/util.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'fs/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (C:\git\polymer3-webpack-starter\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at getPkgMain (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:16:18)
    at bareName (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:25:18)
    at getModuleConfig (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:43:25)
    at PluginPass.CallExpression (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:96:27)
    at newFn (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:53:20)
```

My added dependencies are:
```
    "amazon-cognito-identity-js": "^2.0.27",
    "aws-amplify": "^1.1.1",
    "aws-appsync": "^1.3.4",
```

I have been trying various ideas from https://stackoverflow.com/questions/39249237/node-cannot-find-module-fs-when-using-webpack but with no success.

Any ideas, pointers that may help?

Thanks!

**Comment by web-padawan** [comment]
Hi! This is the issue of `babel-plugin-template-html-minifier`:

https://github.com/goto-bus-stop/babel-plugin-template-html-minifier/blob/234528d3a0f52f69a0563bcfe39343ac5ea49959/index.js#L16

So, you should report it there, and comment that plugin in your Babel config until it gets fixed.

**Comment by coreyfarrell** [comment]
babel-plugin-template-html-minifier@2.0.1 is now released with the fix for this issue.

**Comment by web-padawan** [comment]
Closing per above comment. Thanks for the quick fix!
