### ISSUE TITLE
Suddenly my build failed with a strange error...

### ISSUE THREAD

**Issue by andersforsell** [web-padawan/polymer3-webpack-starter#38]
Hi,

I have been successfully using this template for building my project that uses Polymer 3 and Vaadin components. After upgrading my tools (node/npm) and dependencies I suddenly get an error that I can't seem to fix (see below).

Have tried to find a solution for this, but if you have any pointer it would be really appreciated.

I suspect Babel, and my target is no modules and ie11 (bundling for a Cordova app).

Thanks, 
Anders

```
ERROR in ./node_modules/lodash/lodash.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\lodash\lodash.js: Unexpected token (4996:5)

  4994 | 
  4995 |         // Mimic the constructor's `return`behavior. // See https://es5.github.io/#x13.2.2 for more details. return isObject(result) ? result : thisBinding; }; } /** * Creates a function that wraps `func` to enable currying.
> 4996 |      *
       |      ^
  4997 |      * @private
  4998 |      * @param {Function} func The function to wrap.
  4999 |      * @param {number} bitmask The bitmask flags. See `createWrap` for more details.
    at Parser.raise (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:6344:17)
    at Parser.unexpected (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:7659:16)
    at Parser.parseExprAtom (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8828:20)
    at Parser.parseExprSubscripts (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8413:23)
    at Parser.parseMaybeUnary (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8393:21)
    at Parser.parseExprOps (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8280:23)
    at Parser.parseMaybeConditional (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8253:23)
    at Parser.parseMaybeAssign (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8200:21)
    at Parser.parseExpression (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8148:23)
    at Parser.parseStatementContent (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9917:23)
    at Parser.parseStatement (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9788:17)
    at Parser.parseBlockOrModuleBlockBody (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10364:25)
    at Parser.parseBlockBody (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10351:10)
    at Parser.parseBlock (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10335:10)
    at Parser.parseFunctionBody (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9408:24)
    at Parser.parseFunctionBodyAndFinish (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9378:10)
    at withTopicForbiddingContext (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10498:12)
    at Parser.withTopicForbiddingContext (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9683:14)
    at Parser.parseFunction (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10497:10)
    at Parser.parseFunctionExpression (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8864:17)
    at Parser.parseExprAtom (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8777:21)
    at Parser.parseExprSubscripts (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8413:23)
    at Parser.parseMaybeUnary (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8393:21)
    at Parser.parseExprOps (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8280:23)
    at Parser.parseMaybeConditional (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8253:23)
    at Parser.parseMaybeAssign (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8200:21)
    at Parser.parseExpression (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:8148:23)
    at Parser.parseReturnStatement (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10157:28)
    at Parser.parseStatementContent (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9836:21)
    at Parser.parseStatement (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9788:17)
    at Parser.parseBlockOrModuleBlockBody (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10364:25)
    at Parser.parseBlockBody (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10351:10)
    at Parser.parseBlock (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10335:10)
    at Parser.parseFunctionBody (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9408:24)
    at Parser.parseFunctionBodyAndFinish (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:9378:10)
    at withTopicForbiddingContext (C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp\node_modules\@babel\parser\lib\index.js:10498:12)
 @ ./node_modules/@aws-amplify/analytics/lib/Providers/AmazonPersonalizeProvider.js 164:15-32
 @ ./node_modules/@aws-amplify/analytics/lib/Providers/index.js
 @ ./node_modules/@aws-amplify/analytics/lib/index.js
 @ ./node_modules/aws-amplify/lib/index.js
 @ ./src/aws-api/mint-appsync.js
 @ ./src/app/mint-app.js
 @ ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 2.36 KiB {0} [built]
    [2] (webpack)/buildin/global.js 537 bytes {0} [built]
    [3] (webpack)/buildin/module.js 552 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mint-app@1.1.0 build: `webpack --env production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mint-app@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aforsell\AppData\Roaming\npm-cache\_logs\2019-07-01T15_13_27_900Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mint-app@1.1.0 postinstall: `node utils/generate-helpers.js && npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mint-app@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aforsell\AppData\Roaming\npm-cache\_logs\2019-07-01T15_13_28_004Z-debug.log
PS C:\git\ebitool-mint\mint-gwt-ui\src\main\webapp>
```

**Comment by andersforsell** [comment]
Actually it seems to be the `uglify-template-string-loader` causing this, filed https://github.com/Flamme13/uglify-template-string-loader/issues/1

**Comment by web-padawan** [comment]
Closing per above comment.
